### ISSUE TITLE
RxAnimationBuilder addPre/PostTransform actions 

### ISSUE THREAD

**Issue by laszlo-galosi** [0ximDigital/RxAnimations#3]
It would be great if we can add preTransform and postTransform actions to the RxAnimationBuilder, which is called before/after  the main animations. Something like this:

```
public RxAnimationBuilder addPreTransformAction( Action1<ViewPropertyAnimatorCompat>... actions) {
        Observable.from(actions)
              .subscribe(action -> this.preTransformActions.add(action));
        return this;
}
```

**Comment by 0ximDigital** [comment]
Great idea!

Would you like to submit PR for that?
If not, I will add this to the next release soon.

**Comment by laszlo-galosi** [comment]
Yes of course I can do this, and also the RxJava 1.2+ fix, I had done it anyway in my project. I will send the PR for both soon.

**Comment by 0ximDigital** [comment]
Awesome.

Just curious, what do you use postTransform actions for?

**Comment by laszlo-galosi** [comment]
I would use it like an AnimationListener  public void onAnimationEnd(Animation animation).

**Comment by 0ximDigital** [comment]
Ok, but why do you need that?

For the first animation, you get Completable that you can concat with a second animation when the first one ends.
The second animation acts as a postTransform action.

And if you need a side effect when first animation ends, and start another animation as well, you can use .doOnCompleted(() -> sideEffect())

Example:

```Java
RxAnimationBuilder.animate(view)
                          .rotateBy(90)
                          .schedule()
                          .doOnCompleted(() -> Log.i(TAG, "Done with the first one"))
                          .concatWith(RxAnimations.fadeIn(view))
                          .doOnCompleted(() -> Log.i(TAG, "Done with the second one"))
                          .subscribe();
```

What do you think about this approach?

**Comment by laszlo-galosi** [comment]
Yes it make sense sorry, I've rushed a bit with the idea.
 But what about cancelling animation, and doing some action. In this case the the animation never finished normally, so the onCompleted is never called in the AnimateOnSubscribe.runAnimation. Can we cancel any Rx wrapped Animation in some way? Maybe an explicit cancelation should be provided,  with an onAnimationCancelled action in the RxAnimationBuilder.
The preTransform action as the onAnimationStart is still valid request I suppose?

**Comment by 0ximDigital** [comment]
We are doing some pre-transform actions in the RxAnimationBuilder already, so it is possible to implement a method to just add additional actions. Although, just like in the previous comment, if that what you want to do in onAnimationStart is a side effect, it would be more cohesive to just do something like:

```java
.preTransformSideEffect()
.andThen(yourAnimation.schedule())
```

Animation canceling is a good point. I am sure that something can be done, you will get the update :)

**Comment by 0ximDigital** [comment]
Here is the update regarding this issue.

A new `.onAnimationCancel(view -> {...})` method has been added to the `RxAnimationBuilder`.

The main purpose of this method is to only handle views state in between animation start and end.
RxJava API provides methods that can be used to make pre-transform and post-transform actions, and handle global unsubscription as well.

Release version - **0.8.3**
